<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RwSource', 'doctrine');

/**
 * BaseRwSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $url
 * @property Doctrine_Collection $RwRoadwork
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getType()       Returns the current record's "type" value
 * @method string              getUrl()        Returns the current record's "url" value
 * @method Doctrine_Collection getRwRoadwork() Returns the current record's "RwRoadwork" collection
 * @method RwSource            setId()         Sets the current record's "id" value
 * @method RwSource            setName()       Sets the current record's "name" value
 * @method RwSource            setType()       Sets the current record's "type" value
 * @method RwSource            setUrl()        Sets the current record's "url" value
 * @method RwSource            setRwRoadwork() Sets the current record's "RwRoadwork" collection
 * 
 * @package    roadwork
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRwSource extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rw_source');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'rw_source_id',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RwRoadwork', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}