<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RwToRoute', 'doctrine');

/**
 * BaseRwToRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rw_id
 * @property integer $route_id
 * @property Doctrine_Collection $RwRoadwork
 * @property Doctrine_Collection $RwUserRoute
 * 
 * @method integer             getRwId()        Returns the current record's "rw_id" value
 * @method integer             getRouteId()     Returns the current record's "route_id" value
 * @method Doctrine_Collection getRwRoadwork()  Returns the current record's "RwRoadwork" collection
 * @method Doctrine_Collection getRwUserRoute() Returns the current record's "RwUserRoute" collection
 * @method RwToRoute           setRwId()        Sets the current record's "rw_id" value
 * @method RwToRoute           setRouteId()     Sets the current record's "route_id" value
 * @method RwToRoute           setRwRoadwork()  Sets the current record's "RwRoadwork" collection
 * @method RwToRoute           setRwUserRoute() Sets the current record's "RwUserRoute" collection
 * 
 * @package    roadwork
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRwToRoute extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rw_to_route');
        $this->hasColumn('rw_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('route_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RwRoadwork', array(
             'local' => 'rw_id',
             'foreign' => 'id'));

        $this->hasMany('RwUserRoute', array(
             'local' => 'route_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}