<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $email
 * @property string $fullname
 * @property string $validate
 * @property boolean $send_notification
 * @property sfGuardUser $User
 * 
 * @method integer            getId()                Returns the current record's "id" value
 * @method integer            getUserId()            Returns the current record's "user_id" value
 * @method string             getEmail()             Returns the current record's "email" value
 * @method string             getFullname()          Returns the current record's "fullname" value
 * @method string             getValidate()          Returns the current record's "validate" value
 * @method boolean            getSendNotification()  Returns the current record's "send_notification" value
 * @method sfGuardUser        getUser()              Returns the current record's "User" value
 * @method sfGuardUserProfile setId()                Sets the current record's "id" value
 * @method sfGuardUserProfile setUserId()            Sets the current record's "user_id" value
 * @method sfGuardUserProfile setEmail()             Sets the current record's "email" value
 * @method sfGuardUserProfile setFullname()          Sets the current record's "fullname" value
 * @method sfGuardUserProfile setValidate()          Sets the current record's "validate" value
 * @method sfGuardUserProfile setSendNotification()  Sets the current record's "send_notification" value
 * @method sfGuardUserProfile setUser()              Sets the current record's "User" value
 * 
 * @package    roadwork
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('email', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('fullname', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('validate', 'string', 17, array(
             'type' => 'string',
             'length' => 17,
             ));
        $this->hasColumn('send_notification', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}