<?php

/**
 * RwMtqExtentionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RwMtqExtentionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RwMtqExtentionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RwMtqExtention');
    }

	public function getTableByParameter($param, $value){
		
	  $q = $this->createQuery('n');

      if(isset($param)){
      	$q->addWhere($param . " = ?", $value);	
      }

	  return $q->execute();
	}
	
	public function getByDateAndRoad($startDate, $endDate, $roadname){
	  $q = $this->createQuery('n');

      	$q->addWhere("date_trunc('day', \"start_date\") = date_trunc('day', TIMESTAMP '$startDate')");	
      	$q->addWhere("date_trunc('day', \"end_date\") = date_trunc('day', TIMESTAMP '$endDate')");	
      	$q->addWhere("roadname = ?", $roadname);

	  return $q->execute();
	}
}