<?php

/**
 * RwNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RwNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RwNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RwNotification');
    }

	public function getTableWithJoin(Doctrine_Query $q = null){
		
	  if (is_null($q))
	  {
		$q = $this->createQuery('n');
	  }
 

	  $q->leftJoin('n.RwUserRoute r')
	    ->leftJoin('n.RwRoadwork r2')
	    ->leftJoin('n.sfGuardUser s');
	
	return $q->execute();
	}

	public function getTableByParameter($param, $value){
		
	  $q = $this->createQuery('n');

      if(isset($param)){
      	$q->addWhere($param . " = ?", $value);	
      }

	  return $this->getTableWithJoin($q);
	}
	
	public function getUsersWithPendingNotif(){

        //Can't get DISTINCT clause working with the ORM, so let's go for some raw SQL!
		return Doctrine_Manager::getInstance()->getCurrentConnection()
		  ->fetchAssoc('SELECT DISTINCT user_id from rw_notification where "is_sent" = false');

		}
	
	public function getUnsentNotifByUser($userid){

	  $q = $this->createQuery('n');

      $q->addWhere("user_id = ?", $userid);	
      $q->addWhere("is_sent = ?", false);	      

	  return $this->getTableWithJoin($q);
	}
	
	public function getSentNotifByUser($userid){

	  $q = $this->createQuery('n');

      $q->addWhere("user_id = ?", $userid);	
      $q->addWhere("is_sent = ?", true);
      $q->limit(20);	      

	  return $this->getTableWithJoin($q);
	}	
}