<?php

/**
 * RwRoadworkteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RwRoadworkteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RwRoadworkteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RwRoadworkte');
    }
}