<?php

/**
 * RwToRouteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RwToRouteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RwToRouteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RwToRoute');
    }
}