# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

#given the use of esmtp, username and password are overriden by esmtprc file
  mailer:
    class: sfMailer 
    param:
      logging:  %SF_LOGGING_ENABLED% 
      charset:  %SF_CHARSET% 
      delivery_strategy: realtime 
      transport:
        class: Swift_SmtpTransport
        param:
          host:   smtp.gmail.com
          port:   587     
          encryption: tls 
          username: bot@ronomo.net 
          password: f6$h1&SL 


  sfApplyPlugin:
    mail_transport_class: Zend_Mail_Transport_Smtp 
    mail_transport_host: smtp.gmail.com
    mail_transport_options:
      auth: login
      username: bot@ronomo.net
      password: f6$h1&SL 
      ssl: tls
      port: 587
