all:
  mailer:
    class: sfMailer 
    param:
      logging:  %SF_LOGGING_ENABLED% 
      charset:  %SF_CHARSET% 
      delivery_strategy: realtime 
      transport:
        class: Swift_MailTransport 
        param:
          host:	smtp.gmail.com
          port:   587	
          encryption: tls 
          username: bot@zonecone.ca 
          password: 79l!#KnJ 
