all:
  mailer:
    class: sfMailer 
    param:
      logging:  %SF_LOGGING_ENABLED% 
      charset:  %SF_CHARSET% 
      delivery_strategy: realtime 
      transport:
        class: Swift_MailTransport 
        param:
          host: smtp.postmarkapp.com	
          port:  2525 
          encryption: tls 
          username: robot@zonecone.ca 
          password: 79l!#KnJ 
