signinSuccess:
  
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, scaffold.css, style.css, jquery-ui-1.8.7.custom.css]
  
  has_layout: true
  layout: layoutnomap
